version: '3.4'
services:
  web:
    image: nginx:alpine
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
     - /home/pi/Documents/:/usr/share/nginx/html/:ro
    environment:
     - NGINX_PORT=80
    cap_add:
     - NET_BIND_SERVICE
    restart: unless-stopped
    network_mode: host

