---
- name: Bootstrap Pi server
  import_playbook: bootstrap-pi-server.yaml

- name: Install Docker on RPi
  import_playbook: pi-docker-install.yaml

- name: Install AP mode handler
  import_playbook: install-ap-mode-handler.yaml

- name: Install document server
  import_playbook: install-document-server.yaml
