---
- name: Install document server
  hosts: all
  become: true
  remote_user: "{{ hostvars[inventory_hostname].user }}"
  become_user: root
  vars_files:
    - vars/document-server.yaml

  tasks:
    - name: Enforce limit
      ansible.builtin.fail:
        msg: "You must use -l or --limit. To run on all hosts, use -l 'all'."
      when: ansible_limit is not defined

    - name: Make document server install directory
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server
        state: directory
        mode: "0755"
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Make config subdirectory
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server/config
        state: directory
        mode: "0755"
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Make NGINX web root directory
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root
        state: directory
        mode: "0755"
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Make content subdirectory
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}
        state: directory
        mode: "0755"
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Create content symlink
      ansible.builtin.file:
        src: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}
        dest: /home/{{ hostvars[inventory_hostname].user }}/content
        state: link

    - name: Make active wikis content subdirectory
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}/{{ active_wiki_path }}
        state: directory
        mode: "0755"
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Install NGINX index.html
      ansible.builtin.template:
        src: config/document-server/nginx-index.html.j2
        dest: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/index.html
        mode: '0644'
        owner: "{{ hostvars[inventory_hostname].user }}"

    - name: Install NGINX default.conf
      ansible.builtin.template:
        src: config/document-server/nginx-default.conf.j2
        dest: /home/{{ hostvars[inventory_hostname].user }}/document-server/config/nginx-default.conf
        mode: '0644'
        owner: "{{ hostvars[inventory_hostname].user }}"
      notify: Docker compose restart

    - name: Install docker-compose.yaml
      ansible.builtin.template:
        src: config/document-server/docker-compose.yaml.j2
        dest: /home/{{ hostvars[inventory_hostname].user }}/document-server/docker-compose.yaml
        mode: '0644'
        owner: "{{ hostvars[inventory_hostname].user }}"
      notify: Docker compose restart

  handlers:
    - name: Docker compose restart
      ansible.builtin.command:
        cmd: "docker compose --project-directory /home/{{ hostvars[inventory_hostname].user }}/document-server/ restart"
