- name: Sync content to document server
  hosts: all
  become: true
  remote_user: "{{ hostvars[inventory_hostname].user }}"
  become_user: root
  vars_files:
    - vars/document-server.yaml

  tasks:
    - name: Check for local content directory
      ansible.builtin.stat:
        path: "{{ local_content_sync_path }}"
      register: content_dir

    - name: Check for local active wiki directory
      ansible.builtin.stat:
        path: "{{ local_content_sync_path }}/{{ active_wiki_path }}"
      register: wiki_dir

    - name: Sync local directory content directory to remote
      ansible.posix.synchronize:
        src: "{{ local_content_sync_path }}/"
        dest: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}/
        checksum: true
        copy_links: true
        times: true
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude={{ active_wiki_path }}/*"
      notify: Change content permissions
 
    - name: Sync local active wiki directory to remote
      ansible.posix.synchronize:
        src: "{{ local_content_sync_path }}/{{ active_wiki_path }}"
        dest: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}/{{ active_wiki_path }}
        checksum: true
        copy_links: true
        times: true
        delete: true
        recursive: true
      notify:
        - Change content permissions
        - Docker compose restart
   
  handlers:
    - name: Change content permissions
      ansible.builtin.file:
        path: /home/{{ hostvars[inventory_hostname].user }}/document-server/nginx-root/{{ content_path }}/
        state: directory
        owner: "{{ hostvars[inventory_hostname].user }}"
        mode: u=rwX,g=rwX,o=rX
        recurse: true

    - name: Docker compose restart
      ansible.builtin.command:
        cmd: "docker compose --project-directory /home/{{ hostvars[inventory_hostname].user }}/document-server/ restart"
